In [87]:
 import numpy as np 
import pandas as pd

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [6]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [7]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
a = np.full((2,2),7)

In [9]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.random.random((2,2))

array([[0.61139034, 0.19846084],
       [0.00776184, 0.98896626]])

In [11]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
a.shape

(2, 2)

In [14]:
len(a)

2

In [15]:
a.ndim

2

In [16]:
a.size

4

In [17]:
a.dtype

dtype('int64')

In [18]:
a.dtype.name

'int64'

In [19]:
a.astype(int)

array([[7, 7],
       [7, 7]])

In [21]:
a.dot(a)

array([[98, 98],
       [98, 98]])

In [22]:
a = np.array([1,2,3])

In [27]:
b = np.array([(1.5,2,3), (4,5,6)],dtype =  float)

In [26]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype =  float)

In [28]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [29]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [30]:
a

array([1, 2, 3])

In [31]:
b[:1]

array([[1.5, 2. , 3. ]])

In [32]:
c[1,...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [33]:
a[ : :-1]

array([3, 2, 1])

In [51]:
b[[1, 0, 1, 0],
  [0, 1, 2, 0]] #### WHY?

array([4. , 2. , 6. , 1.5])

In [39]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [59]:
b[[1, 0, 1, 0]] [:,[0,1,2,0]] #### WHY? 

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [46]:
my_list = [1, 2, 3, 4]

In [42]:
my_array = np.array(my_list)

In [50]:
my_2darray = np.array([[1,2,3],
                       [4,5,6]])

In [44]:
my_list.insert(0,'!')

In [45]:
my_list

['!', 1, 2, 3, 4]

In [47]:
my_array[1]

2

In [48]:
my_array[0:2]

array([1, 2])

In [49]:
my_2darray[:,0]

array([1, 4])

In [68]:
arrays = [np.array([1,2,3]),
          np.array([5,4,3])]

In [66]:
df5 = pd.DataFrame(np.random.rand(3, 2), index=arrays)

In [67]:
df5

0         1
1 5  0.396839  0.504438
2 4  0.373653  0.763668
3 3  0.426154  0.476309

In [69]:
tuples = list(zip(*arrays))

In [70]:
tuples

[(1, 5), (2, 4), (3, 3)]

In [73]:
index = pd.MultiIndex.from_tuples(tuples,
                                      names=['first', 'second'])

In [74]:
index

MultiIndex(levels=[[1, 2, 3], [3, 4, 5]],
           labels=[[0, 1, 2], [2, 1, 0]],
           names=['first', 'second'])

In [75]:
df6 = pd.DataFrame(np.random.rand(3, 2), index=index)

In [76]:
df6

0         1
first second                    
1     5       0.308690  0.071056
2     4       0.708327  0.586364
3     3       0.737213  0.814937

In [80]:
df6.groupby(level=0).sum()

0         1
first                    
1      0.308690  0.071056
2      0.708327  0.586364
3      0.737213  0.814937

In [84]:
customSum = lambda x: (x+x%2)
df6.groupby(level=0).transform(customSum)

0         1
first second                    
1     5       0.617380  0.142112
2     4       1.416654  1.172728
3     3       1.474427  1.629874